#!/usr/bin/env bash
# Collect the licences of every module linked into the arca binary.
#
# MIT, BSD and Apache-2.0 all require their notice to travel with a binary
# distribution, so the generated file is attached to every release. It is
# generated rather than committed: the list is a function of go.mod, and a
# hand-maintained copy would drift.
set -euo pipefail

out="${1:-THIRD_PARTY_LICENSES.md}"

go mod download

{
	echo "# Third-party licenses"
	echo
	echo "arca is distributed as a statically linked binary. The Go modules below are"
	echo "compiled into it, and their licenses are reproduced in full as those licenses"
	echo "require. arca's own license is MIT; see LICENSE and NOTICE."
	echo
	echo "Generated by \`scripts/third-party-licenses.sh\` on $(date -u +%Y-%m-%d)."
	echo
	echo "The Go standard library and runtime are also linked in, under the Go project's"
	echo "BSD-3-Clause license: https://go.dev/LICENSE"
	echo
} >"$out"

# -deps of the command, not of the module: test-only and tool dependencies are
# not in the binary and do not belong in its notice file.
go list -deps -f '{{with .Module}}{{.Path}}	{{.Version}}	{{.Dir}}{{end}}' ./cmd/arca |
	sort -u | while IFS=$'\t' read -r path version dir; do
	[ -n "$path" ] || continue
	[ "$path" = "github.com/henriquemenezes/arca" ] && continue

	echo "--------------------------------------------------------------------------------" >>"$out"
	echo >>"$out"
	echo "## $path $version" >>"$out"
	echo >>"$out"

	license=""
	if [ -n "$dir" ]; then
		license="$(find "$dir" -maxdepth 1 -iname 'LICENSE*' -o -maxdepth 1 -iname 'LICENCE*' -o -maxdepth 1 -iname 'COPYING*' | sort | head -1)"
	fi

	if [ -n "$license" ]; then
		echo '```' >>"$out"
		cat "$license" >>"$out"
		echo '```' >>"$out"
	else
		echo "License file not found in the module cache; see https://$path" >>"$out"
	fi
	echo >>"$out"
done

echo "wrote $out"
